#!/usr/bin/env bash
./node_modules/.bin/electron-packager . installer --platform=linux,win32 --arch=all --version=0.33.6 --ignore=".git|node_modules/(?!adm-zip)|builds|test" --out=builds --overwrite
 cd builds
 rm -f *.zip
 zip -r installer-win-64.zip installer-win32-x64
 zip -r installer-win-32.zip installer-win32-ia32
 zip -r installer-lnx-64.zip installer-linux-x64
 zip -r installer-lnx-32.zip installer-linux-ia32
